# System language
lang en_US

# Language modules to install
langsupport en_US

# System keyboard
keyboard us

# System mouse
mouse

# System timezone
timezone --utc Etc/UTC

# Root password
rootpw --disabled

# Initial user; password generated by 'openssl passwd -5'
user jxiong --fullname "Jinshan Xiong" --iscrypted --password $5$Oa15T0MYkG9i3Nq/$MunmH1D7rSYCtHDV0g0pja1voJAvXpcQg8vmHmbTQx8

# Reboot after installation
reboot

# Use text mode install
text

# Install OS instead of upgrade
install

# Use CDROM installation media
cdrom

# System bootloader configuration
bootloader --location=mbr

# Clear the Master Boot Record
zerombr yes

# Partition clearing information
clearpart --all

# Disk partitioning information
part / --fstype ext4 --size 1 --grow --asprimary
#part swap --size 200

# System authorization infomation
auth  --useshadow  --enablemd5

# Firewall configuration
firewall --enabled --ssh

# Do not configure the X Window System
skipx

%post --interpreter=/bin/bash
echo ### Redirect output to console
exec < /dev/tty6 > /root/ks.log 2>&1
chvt 6

echo ### Update all packages
apt-get update
apt-get -y upgrade

# Install packages
apt-get install -y openssh-server vim build-essential

echo ### Enable serial console so virsh can connect to the console
systemctl enable serial-getty@ttyS0.service

echo ### Add public ssh key for user
mkdir -m0700 -p /home/jxiong/.ssh
cat > /home/jxiong/.ssh/authorized_keys << END
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC6h3qsw/XA6MURAEC10gCWnvQ25mpYyf/ghIh+fHpKeEPCWCHCiJvF8T2PzcygmNuhyzc68uBIDL3f/hMRNj3IlFHAWjwnZBPOZrFggaoAWQLngQeN3cZJYCOCHzVLzsRhDHj8f55rahTOjQ8Zs/eo9A7Z27nhcH8KUJPLHCmfHw== jxiong@titan
END
chmod 0600 /home/jxiong/.ssh/authorized_keys

echo "jxiong ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/jxiong
chmod 0600 /etc/sudoers.d/jxiong

echo ### Set permissions for user directory and key. Since the "Initial user"
echo ### is added *after* %post commands are executed, I use the UID:GID
echo ### as a hack since I know that the first user added will be 1000:1000.
chown -R 1000:1000 /home/jxiong

echo ### Change back to terminal 1
chvt 1
%end
